Sample 1: TApp Class Reference
TApp Class Reference
#include <app.h>
Public Types
typedef stResult< TCity > myResult
typedef stMetricTree< TCity, TCityDistanceEvaluator > MetricTree
typedef stDummyTree< TCity, TCityDistanceEvaluator > myDummyTree
Public Member Functions
TApp ()
void Init ()
void Run ()
void Done ()
Member Typedef Documentation
typedef stMetricTree< TCity, TCityDistanceEvaluator > TApp::MetricTree
typedef stDummyTree< TCity, TCityDistanceEvaluator > TApp::myDummyTree
This is the type of the Slim-Tree defined by TCity and TCityDistanceEvaluator.
typedef stResult< TCity > TApp::myResult
This is the type used by the result.
Constructor & Destructor Documentation
TApp::TApp () inline
Creates a new instance of this class.
Member Function Documentation
void TApp::Done ()
Deinitialize the application.
Referenced by Init().
void TApp::Init () inline
Initializes the application.
Parameters
pageSize
minOccup
quantidade
prefix
References Done(), and Run().
void TApp::Run ()
Runs the application.
Parameters
DataPath
DataQueryPath
Referenced by Init().
The documentation for this class was generated from the following file:
app.h