Sample 1: TCity Class Reference
TCity Class Reference
#include <city.h>
Public Member Functions
TCity ()
TCity (const string name, double latitude, double longitude)
~TCity ()
double GetLatitude ()
double GetLongitude ()
const string & GetName ()
TCity * Clone ()
bool IsEqual (TCity *obj)
stSize GetSerializedSize ()
const stByte * Serialize ()
void Unserialize (const stByte *data, stSize datasize)
Detailed Description
This class abstracts a city in a map. Each city has a name and a pair latitude/longitude.
In addition to data manipulation methods (such as GetLatitude(), GetName() and others), this class implements the stObject interface. This interface qualifies this object to be indexed by a metric tree implemented by GBDI SlimTree Library.
This interface requires no inheritance (because of the use of class templates in the Structure Layer) but requires the following methods:
TCity() - A default constructor.
Clone() - Creates a clone of this object.
IsEqual() - Checks if this instance is equal to another.
GetSerializedSize() - Gets the size of the serialized version of this object.
Serialize() - Gets the serialzied version of this object.
Unserialize() - Restores a serialzied object.
Since the array which contains the serialized version of the object must be created and destroyed by each object instance, this class will hold this array as a buffer of the serialized version of this instance. This buffer will be created only if required and will be invalidated every time the object changes its values.
The serialized version of the object will be created as follows:
+-------—+--------—+-----—+
| Latitude | Longitude | Name[] |
+-------—+--------—+-----—+
Latitude and Logitude are stored as doubles (2 64-bit IEEE floating point value) and Name[] is an array of chars with no terminator. Since Name[] has a variable size (associated with the name of the city), the serialized form will also have a variable number of bytes.
Version
1.0
Author
Fabio Jun Takada Chino
Constructor & Destructor Documentation
TCity::TCity () inline
Default constructor. It creates a city with no name and longitude and latitude set to 0. This constructor is required by stObject interface.
TCity::TCity (const string name, double latitude, double longitude) inline
Creates a new city.
Parameters
name The name of the city.
latitude Latitude.
longitude Longitude.
TCity::~TCity () inline
Destroys this instance and releases all associated resources.
Member Function Documentation
TCity* TCity::Clone () inline
Creates a perfect clone of this object. This method is required by stObject interface.
Returns
A new instance of TCity wich is a perfect clone of the original instance.
double TCity::GetLatitude () inline
Gets the latitude of the city.
Referenced by TCityDistanceEvaluator::GetDistance2(), and IsEqual().
double TCity::GetLongitude () inline
Gets the longitude of the city.
Referenced by TCityDistanceEvaluator::GetDistance2(), and IsEqual().
const string& TCity::GetName () inline
Gets the name of the city.
stSize TCity::GetSerializedSize () inline
Returns the size of the serialized version of this object in bytes. This method is required by stObject interface.
bool TCity::IsEqual (TCity * obj) inline
Checks to see if this object is equal to other. This method is required by stObject interface.
Parameters
obj Another instance of TCity.
Returns
True if they are equal or false otherwise.
References GetLatitude(), and GetLongitude().
const stByte* TCity::Serialize ()
Returns the serialized version of this object. This method is required by stObject interface.
Warning
If you don't know how to serialize an object, this methos may be a good example.
void TCity::Unserialize (const stByte * data, stSize datasize)
Rebuilds a serialized object. This method is required by stObject interface.
Parameters
data The serialized object.
datasize The size of the serialized object in bytes.
Warning
If you don't know how to serialize an object, this methos may be a good example.
The documentation for this class was generated from the following file:
city.h