Sample 1: TCityDistanceEvaluator Class Reference
TCityDistanceEvaluator Class Reference
#include <city.h>
Public Member Functions
stDistance GetDistance (TCity *obj1, TCity *obj2)
stDistance GetDistance2 (TCity *obj1, TCity *obj2)
Detailed Description
This class implements a metric evaluator for TCity instances. It calculates the distance between cities by performing a euclidean distance between city coordinates (I know it is not accurate but is is only a sample!!!).
It implements the stMetricEvaluator interface. As stObject interface, the stMetricEvaluator interface requires no inheritance and defines 2 methods:
GetDistance() - Calculates the distance between 2 objects.
GetDistance2() - Calculates the distance between 2 objects raised by 2.
Both methods are defined due to optmization reasons. Since euclidean distance raised by 2 is easier to calculate, It will implement GetDistance2() and use it to calculate GetDistance() result.
Version
1.0
Author
Fabio Jun Takada Chino
Member Function Documentation
stDistance TCityDistanceEvaluator::GetDistance (TCity * obj1, TCity * obj2) inline
Returns the distance between 2 cities. This method is required by stMetricEvaluator interface.
Parameters
obj1 Object 1.
obj2 Object 2.
stDistance TCityDistanceEvaluator::GetDistance2 (TCity * obj1, TCity * obj2) inline
Returns the distance between 2 cities raised by the power of 2. This method is required by stMetricEvaluator interface.
Parameters
obj1 Object 1.
obj2 Object 2.
References TCity::GetLatitude(), TCity::GetLongitude(), and operator<<().
The documentation for this class was generated from the following file:
city.h